# Generated by Django 5.2 on 2025-04-05 13:15

import theater.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theater", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="image",
            field=models.ImageField(
                null=True, upload_to=theater.models.play_image_file_path
            ),
        ),
    ]
