# Generated by Django 5.2 on 2025-04-06 00:01

import theater.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theater", "0002_play_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="image",
            field=models.ImageField(
                null=True, upload_to=theater.models.actor_image_file_path
            ),
        ),
    ]
