# Generated by Django 5.2 on 2025-04-06 14:08

import theater.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theater", "0003_actor_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=theater.models.actor_image_file_path
            ),
        ),
        migrations.AlterField(
            model_name="play",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=theater.models.play_image_file_path
            ),
        ),
    ]
