# Generated by Django 5.2 on 2025-04-08 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theater", "0005_alter_play_actors_alter_play_genres"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="performance",
            options={"ordering": ["show_time"]},
        ),
    ]
